from pathlib import Path
import re
p=Path('app/src/main/java/com/ayuemin/ymnik/ui/YmnikApp.kt')
s=p.read_text()

s=s.replace('''    val enabledConnections = state.connectionProfiles.filter { it.id !in state.disabledConnectionIds }\n    var selectedImageConnectionId by remember(mode, enabledConnections.map { it.id }) {\n''','''    val enabledConnections = state.connectionProfiles.filter { it.id !in state.disabledConnectionIds }\n    var selectedTextConnectionId by remember(mode, enabledConnections.map { it.id }) {\n        mutableStateOf(\n            state.activeConnectionProfileId.takeIf { id -> enabledConnections.any { it.id == id } }\n                ?: enabledConnections.firstOrNull()?.id\n        )\n    }\n    var selectedImageConnectionId by remember(mode, enabledConnections.map { it.id }) {\n''',1)

old='''    val selectedImageConnection = enabledConnections.firstOrNull { it.id == selectedImageConnectionId }\n    val models = if (mode == ChatMode.TEXT) {\n        state.availableTextModels\n    } else {\n        if (state.modelCatalogConnectionId == selectedImageConnectionId) state.modelCatalog else emptyList()\n    }\n    val current = if (mode == ChatMode.TEXT) state.textModel else state.imageModel\n\n    LaunchedEffect(mode, selectedImageConnectionId) {\n        if (mode == ChatMode.TEXT) {\n            if (models.isEmpty()) vm.refreshModels(mode)\n        } else {\n            selectedImageConnectionId?.let(vm::loadImageConnectionModels)\n        }\n    }\n'''
new='''    val selectedTextConnection = enabledConnections.firstOrNull { it.id == selectedTextConnectionId }\n    val selectedImageConnection = enabledConnections.firstOrNull { it.id == selectedImageConnectionId }\n    val selectedConnectionId = if (mode == ChatMode.TEXT) selectedTextConnectionId else selectedImageConnectionId\n    val selectedConnection = if (mode == ChatMode.TEXT) selectedTextConnection else selectedImageConnection\n    val models = when {\n        state.modelCatalogConnectionId == selectedConnectionId -> state.modelCatalog\n        mode == ChatMode.TEXT && selectedConnectionId == state.activeConnectionProfileId -> state.availableTextModels\n        else -> emptyList()\n    }\n    val current = if (mode == ChatMode.TEXT) {\n        selectedTextConnectionId?.let(vm::defaultTextModelForConnection).orEmpty()\n    } else state.imageModel\n\n    LaunchedEffect(mode, selectedTextConnectionId, selectedImageConnectionId) {\n        if (mode == ChatMode.TEXT) selectedTextConnectionId?.let(vm::loadConnectionModels)\n        else selectedImageConnectionId?.let(vm::loadImageConnectionModels)\n    }\n'''
assert old in s
s=s.replace(old,new,1)

s=s.replace('''            if (mode == ChatMode.TEXT) "Сейчас: $current" else "Сейчас: ${state.connectionProfiles.firstOrNull { it.id == state.imageConnectionProfileId }?.name ?: "Подключение"} · $current",\n''','''            "Сейчас: ${selectedConnection?.name ?: "Подключение"} · ${current.ifBlank { "не выбрана" }}",\n''',1)

pat=re.compile(r'''        if \(mode == ChatMode\.IMAGE\) \{\n            if \(enabledConnections\.isEmpty\(\)\) \{.*?\n        \}\n        OutlinedTextField\(''',re.S)
rep='''        if (enabledConnections.isEmpty()) {\n            Text(\n                "Нет включённых подключений.",\n                modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp),\n                color = MaterialTheme.colorScheme.onSurfaceVariant\n            )\n        } else {\n            LazyRow(\n                modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 4.dp),\n                horizontalArrangement = Arrangement.spacedBy(7.dp)\n            ) {\n                items(enabledConnections, key = { it.id }) { connection ->\n                    FilterChip(\n                        selected = selectedConnectionId == connection.id,\n                        onClick = {\n                            if (mode == ChatMode.TEXT) selectedTextConnectionId = connection.id\n                            else selectedImageConnectionId = connection.id\n                            query = ""\n                        },\n                        label = { Text(connection.name, maxLines = 1) }\n                    )\n                }\n            }\n            if (mode == ChatMode.IMAGE && selectedConnection?.type == ProviderType.OPENAI_COMPATIBLE) {\n                Text(\n                    "Для совместимого API показан общий список /models. Выберите модель, которая умеет генерацию изображений; запрос отправится на /images/generations.",\n                    modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 4.dp),\n                    style = MaterialTheme.typography.bodySmall,\n                    color = MaterialTheme.colorScheme.onSurfaceVariant\n                )\n            }\n            if (mode == ChatMode.TEXT) {\n                Text(\n                    "У каждого подключения своя модель по умолчанию. Выбор здесь не переключает текущий чат на другой сервис.",\n                    modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 4.dp),\n                    style = MaterialTheme.typography.bodySmall,\n                    color = MaterialTheme.colorScheme.onSurfaceVariant\n                )\n            }\n        }\n        OutlinedTextField('''
s,n=pat.subn(rep,s,1)
assert n==1,n

s=s.replace('''                if (mode == ChatMode.TEXT) vm.refreshModels(mode)\n                else selectedImageConnectionId?.let(vm::loadImageConnectionModels)\n''','''                if (mode == ChatMode.TEXT) selectedTextConnectionId?.let(vm::loadConnectionModels)\n                else selectedImageConnectionId?.let(vm::loadImageConnectionModels)\n''',1)

s=s.replace('''                            if (mode == ChatMode.TEXT) vm.selectModel(mode, modelInfo.id)\n                            else selectedImageConnectionId?.let { vm.selectImageModel(it, modelInfo.id) }\n''','''                            if (mode == ChatMode.TEXT) selectedTextConnectionId?.let { vm.selectDefaultTextModel(it, modelInfo.id) }\n                            else selectedImageConnectionId?.let { vm.selectImageModel(it, modelInfo.id) }\n''',1)

p.write_text(s)
